FROM rust:1.85-bullseye AS builder
WORKDIR /usr/src/app

COPY . .

ARG SUPABASE_JWT_SECRET
ENV SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
ENV SQLX_OFFLINE=true
RUN cargo build --release

FROM debian:bullseye AS runner
COPY --from=builder /usr/src/app/target/release/server /usr/bin/server
COPY --from=builder /usr/src/app/migrations /usr/src/
ENV MIGRATIONS_PATH=/usr/src/
ENTRYPOINT [ "/usr/bin/server" ]
